SAMPLES_PATH = "poses"
VIDEO_PLACEHOLDER = "no_camera.jpg"
FONT_SIZE = 0.5
DEFAULT_VOLUME = 100
VOLUME = DEFAULT_VOLUME // 100
HIGH_SCORE = 0
TIMER = 2
MAX_SCORE = 1000
MAX_PLAYERS = 1
PLAYERS = 1
ROUNDS = 3
MAX_ROUNDS = 100
TEST = 8
MAX = 10
# Backgrounds
MAIN_MENU_BACKGROUND = "main_background.png"